### ISSUE TITLE
SpiecEasi is not compatible with huge v1.3.0

### ISSUE THREAD

**Issue by dileep-kishore** [zdk123/SpiecEasi#68]
The `huge` package had a [new release](https://github.com/cran/huge/releases) a few days ago and it looks like it has a few breaking changes. Most notably I get this error - `Error: 'huge.mb' is not an exported object from 'namespace:huge'` when I try to use the `mb` method of `SpiecEasi`.

I was able to resolve this issue when I reverted `huge` back to v1.2.7. Maybe you can "fix" the `huge` dependency on this version.

**Comment by zdk123** [comment]
great catch, thanks!

**Comment by zdk123** [comment]
Looks like `huge.mb` is no longer an exported function. Simple fix is to call `huge::huge` and provide `method='mb'` as an argument. I am already doing this with glasso, so this may have been an inadvertent regression.

**Comment by zdk123** [comment]
Should be fixed in c21593f61b8ea9a8e510d489ba78ef053a28a9c3 waiting for Travis checks.

**Comment by dileep-kishore** [comment]
Thanks for looking into this so quickly and thanks for the great package!

**Comment by mauraeva** [comment]
I am having the same problem!
Applying data transformations...
Error in switch(sel.criterion, stars = "stars", bstars = "stars", stop("Unknown selection criterion")) :
 EXPR must be a length 1 vector

**Comment by zdk123** [comment]
Fixed on master / v1.0.5 release.

**Comment by mhibberd** [comment]
Hey all. I'm running v1.0.5 of SpiecEasi and v1.3.0 of huge, pulled from master and still seeing this issue!

**Comment by zdk123** [comment]
@mhibberd: can you post output of `sessionInfo`? The exact code and/or error message would be useful too.

**Comment by mhibberd** [comment]
Apologies- you shouldn't have to tell me...

```
data(amgut1.filt)
se.mb.amgut <- spiec.easi(amgut1.filt, method='mb', lambda.min.ratio=1e-2,
                          nlambda=20, pulsar.params=list(rep.num=50))
sebeta <- symBeta(getOptBeta(se.mb.amgut), mode='maxabs') # symmetrize a beta coefficient matrix
```
Error in if (nrow(beta) != ncol(beta)) { : argument is of length zero
```
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] SpiecEasi_1.0.5     gridExtra_2.3       phangorn_2.4.0      ape_5.2             vegan_2.5-4         lattice_0.20-38     permute_0.9-4       randomForest_4.6-14 ggpubr_0.2          magrittr_1.5       
[11] forcats_0.4.0       stringr_1.4.0       dplyr_0.8.0.1       purrr_0.3.1         readr_1.3.1         tidyr_0.8.2         tibble_2.0.1        ggplot2_3.1.0       tidyverse_1.2.1     phyloseq_1.26.1    

loaded via a namespace (and not attached):
 [1] Biobase_2.42.0      httr_1.4.0          VGAM_1.1-1          jsonlite_1.6        splines_3.5.2       foreach_1.4.4       modelr_0.1.4        assertthat_0.2.0    stats4_3.5.2        cellranger_1.1.0   
[11] yaml_2.2.0          pillar_1.3.1        backports_1.1.3     glue_1.3.0          quadprog_1.5-5      XVector_0.22.0      rvest_0.3.2         colorspace_1.4-0    Matrix_1.2-15       plyr_1.8.4         
[21] pkgconfig_2.0.2     broom_0.5.1         haven_2.1.0         pulsar_0.3.5        zlibbioc_1.28.0     scales_1.0.0        huge_1.3.0          mgcv_1.8-26         generics_0.0.2      IRanges_2.16.0     
[31] withr_2.1.2         BiocGenerics_0.28.0 lazyeval_0.2.1      cli_1.0.1           survival_2.43-3     crayon_1.3.4        readxl_1.3.0        nlme_3.1-137        MASS_7.3-51.1       xml2_1.2.0         
[41] tools_3.5.2         data.table_1.12.0   hms_0.4.2           Rhdf5lib_1.4.2      S4Vectors_0.20.1    munsell_0.5.0       cluster_2.0.7-1     Biostrings_2.50.2   ade4_1.7-13         compiler_3.5.2     
[51] rlang_0.3.1         rhdf5_2.26.2        grid_3.5.2          iterators_1.0.10    biomformat_1.10.1   rstudioapi_0.9.0    igraph_1.2.4        gtable_0.2.0        codetools_0.2-15    multtest_2.38.0    
[61] reshape2_1.4.3      R6_2.4.0            lubridate_1.7.4     knitr_1.21          fastmatch_1.1-0     stringi_1.3.1       parallel_3.5.2      Rcpp_1.0.0          tidyselect_0.2.5    xfun_0.4           
>```

**Comment by zdk123** [comment]
@mhibberd: that is actually a different issue that I am already tracking in #72

**Comment by zdk123** [comment]
Please try out 1.0.6, now on master
